language: python
python:
  - "3.6"
script:
  - pipenv run coverage run manage.py test --noinput && coverage report
install:
  - pip install pipenv
  - pipenv install --dev
before_script:
  - mysql -e 'create database piquantmag;'
  - pipenv run python manage.py migrate
  - npm ci
  - npm run build
notifications:
  email: false
