# Generated by Django 2.0 on 2018-01-29 00:55

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import markupfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('title', models.CharField(max_length=255)),
                ('synopsis', models.TextField()),
                ('slug', models.SlugField(unique=True)),
                ('body', markupfield.fields.MarkupField(rendered_field=True)),
                ('body_markup_type', models.CharField(choices=[('', '--'), ('markdown', 'markdown')], default='markdown', editable=False, max_length=30)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('_body_rendered', models.TextField(editable=False)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefixes', models.CharField(blank=True, max_length=255, null=True)),
                ('given_names', models.CharField(max_length=255)),
                ('middle_names', models.CharField(blank=True, max_length=255, null=True)),
                ('family_names', models.CharField(max_length=255)),
                ('suffixes', models.CharField(blank=True, max_length=255, null=True)),
                ('display_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('publication_date', models.DateTimeField()),
                ('synopsis', models.TextField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='article',
            name='authors',
            field=models.ManyToManyField(to='zine.Author'),
        ),
        migrations.AddField(
            model_name='article',
            name='issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zine.Issue'),
        ),
        migrations.AlterModelManagers(
            name='article',
            managers=[
                ('articles', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='issue',
            managers=[
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('type', models.CharField(choices=[('PullQuoteComponentRenderer', 'PullQuoteComponentRenderer'), ('BodyComponentRenderer', 'BodyComponentRenderer'), ('ImageComponentRenderer', 'ImageComponentRenderer')], max_length=50)),
                ('body', markupfield.fields.MarkupField(blank=True, null=True, rendered_field=True)),
                ('body_markup_type', models.CharField(choices=[('', '--'), ('markdown', 'markdown')], default='markdown', editable=False, max_length=30)),
                ('quote', models.CharField(blank=True, max_length=100, null=True)),
                ('_body_rendered', models.TextField(editable=False, null=True)),
                ('image_alt_text_override', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(height_field='height', upload_to='', width_field='width')),
                ('alt_text', models.CharField(max_length=100)),
                ('height', models.PositiveSmallIntegerField()),
                ('width', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='_body_rendered',
        ),
        migrations.RemoveField(
            model_name='article',
            name='body',
        ),
        migrations.RemoveField(
            model_name='article',
            name='body_markup_type',
        ),
        migrations.AlterField(
            model_name='article',
            name='synopsis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='component',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zine.Article'),
        ),
        migrations.AddField(
            model_name='component',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zine.Image'),
        ),
        migrations.AddField(
            model_name='article',
            name='cover_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zine.Image'),
        ),
        migrations.AlterModelManagers(
            name='article',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='authors',
            field=models.ManyToManyField(blank=True, to='zine.Author'),
        ),
    ]
