# Generated by Django 2.0 on 2018-01-14 18:17

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import markupfield.fields


class Migration(migrations.Migration):

    replaces = [('zine', '0001_initial'), ('zine', '0002_auto_20180114_1314')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('title', models.CharField(max_length=255)),
                ('synopsis', models.TextField()),
                ('slug', models.SlugField(unique=True)),
                ('body', markupfield.fields.MarkupField(rendered_field=True)),
                ('body_markup_type', models.CharField(choices=[('', '--'), ('markdown', 'markdown')], default='markdown', editable=False, max_length=30)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('_body_rendered', models.TextField(editable=False)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefixes', models.CharField(blank=True, max_length=255, null=True)),
                ('given_names', models.CharField(max_length=255)),
                ('middle_names', models.CharField(blank=True, max_length=255, null=True)),
                ('family_names', models.CharField(max_length=255)),
                ('suffixes', models.CharField(blank=True, max_length=255, null=True)),
                ('display_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('publication_date', models.DateTimeField()),
                ('synopsis', models.TextField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='article',
            name='authors',
            field=models.ManyToManyField(to='zine.Author'),
        ),
        migrations.AddField(
            model_name='article',
            name='issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zine.Issue'),
        ),
        migrations.AlterModelManagers(
            name='article',
            managers=[
                ('articles', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='issue',
            managers=[
                ('issues', django.db.models.manager.Manager()),
            ],
        ),
    ]
