# Generated by Django 2.0 on 2018-01-14 18:14

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('zine', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='article',
            managers=[
                ('articles', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='issue',
            managers=[
                ('issues', django.db.models.manager.Manager()),
            ],
        ),
    ]
