# Generated by Django 2.0 on 2018-01-27 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zine', '0002_authoring'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='article',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='issue',
            managers=[
            ],
        ),
    ]
