# Generated by Django 2.0 on 2018-01-28 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zine', '0003_change_manager_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='authors',
            field=models.ManyToManyField(blank=True, to='zine.Author'),
        ),
    ]
