# Generated by Django 2.0 on 2018-02-11 22:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('zine', '0004_articlepreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepreview',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='UUID'),
        ),
    ]
