# Generated by Django 2.0.4 on 2018-05-05 12:41

from django.db import migrations, models
import markupfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('zine', '0005_fake_the_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='_synopsis_rendered',
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='synopsis_markup_type',
            field=models.CharField(choices=[('', '--'), ('markdown', 'markdown')], default='markdown', editable=False, max_length=30),
        ),
        migrations.AddField(
            model_name='issue',
            name='_synopsis_rendered',
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='synopsis_markup_type',
            field=models.CharField(choices=[('', '--'), ('markdown', 'markdown')], default='markdown', editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='article',
            name='synopsis',
            field=markupfield.fields.MarkupField(blank=True, null=True, rendered_field=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='synopsis',
            field=markupfield.fields.MarkupField(blank=True, null=True, rendered_field=True),
        ),
    ]
