# Generated by Django 2.0.4 on 2018-05-05 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zine', '0006_use_markup_field_for_synopses'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='cover_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zine.Image'),
        ),
    ]
