# Generated by Django 2.0.4 on 2018-05-07 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zine', '0007_issue_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
